name: Portainer v2
#version: 2.19.4
version: 2.16.1a
slug: portainer2
description: Manage your Docker environment with ease
advanced: true

ingress: true
ingress_port: 1337

startup: services
panel_icon: mdi:docker

#homeassistant: 2024.2.3
homeassistant: 2021.12.10

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
map:
  - ssl
ports:
  8000/tcp:
  9443/tcp: 9443
ports_description:
  8000/tcp: Edge Agent Api (Enable when managing remote edge agents)
  9090/tcp: Frontend port (https)
boot: auto
hassio_api: true
hassio_role: default
docker_api: true
options: { }
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  agent_secret: str?

# TODO Find out how to mount a host dir / volume to keep the portainer data for backup etc. Current
# image/setup does save the data under: /data/....
